apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Tạo trước để Ingress có thể request cert
spec:
  selfSigned: {}
