apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/basic-auth
stringData:
  username: keycloak
  password: keycloak-secret-password  # TODO: Replace with SealedSecret or ExternalSecret in production
