apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  storage:
    size: 2Gi

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
      wal_buffers: "8MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      wal_level: "replica"
      max_wal_senders: "10"
      max_replication_slots: "10"
      checkpoint_completion_target: "0.9"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

  primaryUpdateStrategy: unsupervised
  minSyncReplicas: 1
  maxSyncReplicas: 2
  switchoverDelay: 60
  startDelay: 30
  stopDelay: 30
  enableSuperuserAccess: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred

  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_

  monitoring:
    enablePodMonitor: true
